name: Soundchameleon
favicon: null
layout_spectrum: 0.49542
typography_spectrum: 0.53646
title: 'Alternative DJing '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#a4a691'
    - '#7a6972'
    - '#002f4a'
  brandStrength: 0.3844891448970884
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
